### ISSUE TITLE
Issue with @nestjs/graphql

### ISSUE THREAD

**Issue by rslowinski** [express-rate-limit/rate-limit-redis#196]
### Description

I've installed latest version (7.0.2) of express-rate-limit and wanted to add Redis store. However, when I tried to run app when installed latest rate-limit-redis (4.1.0) I got following error when running my nest backend:

```
[0] Error: Cannot find module '@nestjs/graphql'
[0] Require stack:
[0] - /app_name/backend/node_modules/ncsrf/dist/guards/csrf.guard.js
[0] - /app_name/backend/node_modules/ncsrf/dist/decorators/csrf.decorator.js
[0] - /app_name/backend/node_modules/ncsrf/dist/decorators/index.js
[0] - /app_name/backend/node_modules/ncsrf/dist/index.js
[0] - /app_name/backend/src/main.ts
[0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[0]     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/app_name/backend/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
[0]     at Function.Module._resolveFilename (/app_name/backend/node_modules/tsconfig-paths/src/register.ts:115:36)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0]     at require (node:internal/modules/cjs/helpers:102:18)
[0]     at Object.<anonymous> (/app_name/backend/node_modules/ncsrf/dist/guards/csrf.guard.js:14:19)
[0]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[0]     at Object.require.extensions.<computed> [as .js] (/app_name/backend/node_modules/ts-node/src/index.ts:1608:43) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     '/app_name/backend/node_modules/ncsrf/dist/guards/csrf.guard.js',
[0]     '/app_name/backend/node_modules/ncsrf/dist/decorators/csrf.decorator.js',
[0]     '/app_name/backend/node_modules/ncsrf/dist/decorators/index.js',
[0]     '/app_name/backend/node_modules/ncsrf/dist/index.js',
[0]     '/app_name/backend/src/main.ts'
[0]   ]
[0] }
```

### Library version

4.1.0

### Node version

16.13.0

### Typescript version (if you are using it)

4.7.4

### Module system

ESM

**Comment by gamemaker1** [comment]
Hi,

I don't see anything that ties this issue to `rate-limit-redis` :/

We could try a couple of things to narrow down the issue:

1. Could you please try deleting and reinstalling the node modules?
2. Could you try downgrading to version 4.0.0, or version 3.1.0 of `rate-limit-redis` and see if the issue still occurs?
3. Also, could you please share your tsconfig.json?

Regards,
Vedant

**Comment by gamemaker1** [comment]
One more thing: what command are you using to run the app? The stack trace seems to point to an error when ts-node is resolving modules.

**Comment by rslowinski** [comment]
thanks a lot @gamemaker1 for thoughtful answers! it appeared to be flaky - after removing node_modules, IDE cache etc it started working

**Comment by gamemaker1** [comment]
Great!
